# Generated by Django 5.2.5 on 2025-09-01 19:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "processo_convocacao_uuid",
                    models.UUIDField(verbose_name="UUID do Processo de Convocação"),
                ),
                (
                    "processo_convocacao_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Processo de Convocação"
                    ),
                ),
                ("cargo_uuid", models.UUIDField(verbose_name="UUID do Cargo")),
                (
                    "cargo_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Cargo"),
                ),
                (
                    "data_escolha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Publicação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda de Convocação",
                "verbose_name_plural": "Agendas de Convocação",
                "db_table": "agenda",
                "ordering": ["-criado_em"],
            },
        ),
    ]
