# Generated by Django 5.2.5 on 2025-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="classificacao",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Classificação"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="escolha_em",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Escolha"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="hora_convocacao_fim",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Fim da Convocação"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="hora_convocacao_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora de Início da Convocação"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[("Presencial", "Presencial"), ("Online", "Online")],
                max_length=20,
                null=True,
                verbose_name="Modalidade",
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="nomeacao_em",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nomeação"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="retardatario",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Retardatário"
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="sessao",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Sessão"
            ),
        ),
    ]
