# Generated by Django 5.2.5 on 2025-11-12 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_agenda_classificacao_agenda_escolha_em_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agenda",
            options={
                "ordering": ["escolha_em", "hora_convocacao_inicio"],
                "verbose_name": "Agenda de Convocação",
                "verbose_name_plural": "Agendas de Convocação",
            },
        ),
        migrations.AddField(
            model_name="agenda",
            name="candidatos_uuids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="UUIDs dos Candidatos",
            ),
        ),
    ]
