# Generated by Django 5.2.5 on 2025-11-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_alter_agenda_options_agenda_candidatos_uuids"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="cargo_codigo",
            field=models.CharField(
                default="", max_length=20, verbose_name="Código do Cargo"
            ),
        ),
    ]
